pipeline {
    agent any
    tools {
        maven 'maven-3'
    }
    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')
        disableConcurrentBuilds()
        skipDefaultCheckout()
    }
    stages {
        stage('Clean up') { 
            steps {
                deleteDir()
            }
        }
        stage('Clone') {
            steps {
                git credentialsId: '4f8dcf06-a320-4afd-914d-d7fa62be287c', url: 'git@github.com:ddrobnjak/simple-java-maven-app.git'
            }
        }
        stage('Build') {
            steps {
                sh """ echo "1-${params.BRANCH}" """
                echo "2-$params.BRANCH"
                sh "mvn -B clean package -DskipTests -Dbranch=${params.BRANCH}"
            }
        }
        
    }
    post {
        success {
                archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false
        } 
    }
}
