pipeline {
    agent any
    tools {
        maven 'maven-3'
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        skipDefaultCheckout()
    }
    stages {
        stage('Clean up') { 
            steps {
                deleteDir()
            }
        }
        stage('Clone') {
            steps {
                git credentialsId: '4f8dcf06-a320-4afd-914d-d7fa62be287c', url: 'git@github.com:ddrobnjak/simple-java-maven-app.git'
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'subDir']],
                          userRemoteConfigs: [[credentialsId: '4f8dcf06-a320-4afd-914d-d7fa62be287c', url: 'git@github.com:ddrobnjak/go-simple-app.git']]])
            }
        }
        stage('Build') {
            steps {
                sh "mvn -B clean package -DskipTests"
            }
        }
        
    }
    post {
        success {
                archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false
        } 
    }
}
