pipeline {
    agent any
    tools {
        maven 'maven-3'
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        skipDefaultCheckout()
    }
    environment {
        ARTIFACTORY_ACCESS_TOKEN = credentials('artifactory-access-token')
    }
    stages {
        stage('Clean up') { 
            steps {
                deleteDir()
            }
        }
        stage('Clone') {
            steps {
                git credentialsId: '4f8dcf06-a320-4afd-914d-d7fa62be287c', url: 'git@github.com:ddrobnjak/simple-java-maven-app.git'
            }
        }
        stage('Build') {
            steps {
                sh "mvn -B clean package -DskipTests"                 
            }
        }
        stage('Upload artifact') {
            steps {
                sh "echo skip"
                //sh 'jf rt upload --url http://3.231.159.32:8082/artifactory --access-token ${ARTIFACTORY_ACCESS_TOKEN} target/*.jar java-hello-world/'
            }
        }
    }
    post {
        success {
                archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false
                sh "echo $JENKINS_HOME/jobs/$JOB_NAME/builds/$BUILD_NUMBER/archive/target/my-app-1.0.jar"
        }
    }
}
